version: 2
jobs:
  build:
    working_directory: ~/blockly
    parallelism: 1
    docker:
    - image: circleci/node:6.13-browsers
    steps:
    - checkout
    - restore_cache:
        keys:
        - v3-dep-{{ checksum "package.json" }}
    - run: npm install
    - save_cache:
        key: v3-dep-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run: npm test
